name: Make Doc

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/make.doc.yml'
      - 'coredns.1.md'
      - 'corefile.5.md'
      - 'plugin/*/README.md'

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.1'
      -
        name: Update Docs
        run: |
          ./.github/fixup_file_mtime.sh
          make -f Makefile.doc
      -
        name: Set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "coredns-auto-go-mod-tidy[bot]"
          git config user.email "coredns-auto-go-mod-tidy[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      -
        name: Commit and push changes
        run: |
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m 'auto make -f Makefile.doc'
            git push
          fi
